[package]
name = "upstash-ratelimit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert-panic = "1.0.1"
chrono = "0.4"
redis = {version = "0.24.0", features = ["tokio-comp"]}
regex = "1.10.3"
