[package]
name = "with-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15"
redis = {version = "0.24.0", features = ["tokio-comp"]}
upstash-ratelimit-rs = "1.0.0"
